# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: phpVirtualbox"
  org.opencontainers.image.description: "Manage a running Virtualbox server through Home Assistant"
  org.opencontainers.image.vendor: "Volantis Development"
  org.opencontainers.image.authors: "Ben McClure <ben@volantisdev.com>"
  org.opencontainers.image.source: "https://github.com/bmcclure/ha-phpvirtualbox-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
